// @ts-nocheck
import React from 'react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import { WorkflowAdapter } from '../adapters/WorkflowAdapter';
import { CaseExplorerPage } from './CaseExplorerPage';
import { CaseDetailPage } from './CaseDetailPage';
import fs from 'fs';
import path from 'path';

// Helper to read the actual JSON artifacts generated by Python
function readArtifact(split: string) {
  const dataPath = path.resolve(__dirname, `../../public/data/${split}.json`);
  return JSON.parse(fs.readFileSync(dataPath, 'utf-8'));
}

describe('Phase 5 UI Tests', () => {
  let devData;

  beforeEach(() => {
    devData = readArtifact('dev');
  });

  it('Case Explorer renders', () => {
    render(<CaseExplorerPage data={devData} onNavigateCase={vi.fn()} />);
    expect(screen.getByText('Case Explorer')).toBeDefined();
  });

  it('Search finds a known case', () => {
    const { container } = render(<CaseExplorerPage data={devData} onNavigateCase={vi.fn()} />);
    const searchInput = screen.getByPlaceholderText('e.g. RZP_HOLDOUT_000048');
    fireEvent.change(searchInput, { target: { value: 'RZP_DEV_000001' } });
    
    // Total cases shown text updates
    expect(screen.getByText(/Showing 1–1 of 1 cases/)).toBeDefined();
  });

  it('Search is case-insensitive', () => {
    render(<CaseExplorerPage data={devData} onNavigateCase={vi.fn()} />);
    const searchInput = screen.getByPlaceholderText('e.g. RZP_HOLDOUT_000048');
    fireEvent.change(searchInput, { target: { value: 'rzp_dev_000001' } });
    expect(screen.getByText(/Showing 1–1 of 1 cases/)).toBeDefined();
  });

  it('Empty search produces all cases', () => {
    render(<CaseExplorerPage data={devData} onNavigateCase={vi.fn()} />);
    const searchInput = screen.getByPlaceholderText('e.g. RZP_HOLDOUT_000048');
    fireEvent.change(searchInput, { target: { value: 'RZP_DEV_000001' } });
    fireEvent.change(searchInput, { target: { value: '' } });
    expect(screen.getByText(/Showing 1–25 of 100 cases/)).toBeDefined();
  });

  it('Route filter works', () => {
    render(<CaseExplorerPage data={devData} onNavigateCase={vi.fn()} />);
    const selects = screen.getAllByRole('combobox');
    const routeSelect = selects[0]; // Route is second select after page size, wait no, page size is at the bottom. The first is Route!
    fireEvent.change(routeSelect, { target: { value: 'AI_INVESTIGATOR' } });
    expect(screen.getByText(/Showing 1–5 of 5 cases/)).toBeDefined();
  });

  it('Multiple filters combine correctly', () => {
    render(<CaseExplorerPage data={devData} onNavigateCase={vi.fn()} />);
    const selects = screen.getAllByRole('combobox');
    const routeSelect = selects[0];
    const policySelect = selects[2];
    
    fireEvent.change(routeSelect, { target: { value: 'AI_INVESTIGATOR' } });
    fireEvent.change(policySelect, { target: { value: 'ALLOW' } });
    
    // There might be fewer than 5 allowed AI cases
    expect(screen.getByText(/Showing 1–/)).toBeDefined();
  });

  it('Pagination works', () => {
    render(<CaseExplorerPage data={devData} onNavigateCase={vi.fn()} />);
    const nextBtn = screen.getByText('Next');
    fireEvent.click(nextBtn);
    expect(screen.getByText(/Showing 26–50 of 100 cases/)).toBeDefined();
  });

  it('Case detail opens and displays correct reference', () => {
    const caseId = devData.cases[0].operational_reference_id;
    render(<CaseDetailPage data={devData} caseId={caseId} onBack={vi.fn()} />);
    expect(screen.getAllByText(caseId).length).toBeGreaterThan(0);
    expect(screen.getAllByText('Reconciliation').length).toBeGreaterThan(0);
  });

  it('Deterministic case does not display fake AI investigation', () => {
    const caseId = devData.cases.find(c => c.reconciliation.route === 'DETERMINISTIC').operational_reference_id;
    render(<CaseDetailPage data={devData} caseId={caseId} onBack={vi.fn()} />);
    expect(screen.getByText('Not required for this case. Resolved deterministically.')).toBeDefined();
  });

  it('AI case displays investigation', () => {
    const caseId = devData.cases.find(c => c.reconciliation.route === 'AI_INVESTIGATOR').operational_reference_id;
    render(<CaseDetailPage data={devData} caseId={caseId} onBack={vi.fn()} />);
    expect(screen.getByText('AI ADVISORY')).toBeDefined();
  });

  it('Missing case produces Case Not Found', () => {
    render(<CaseDetailPage data={devData} caseId="NON_EXISTENT" onBack={vi.fn()} />);
    expect(screen.getByText('Case Not Found')).toBeDefined();
  });

});
