// @ts-nocheck
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { WorkflowAdapter } from './WorkflowAdapter';
import fs from 'fs';
import path from 'path';
import type { WorkflowOutput } from '../types/workflow';

// Helper to read the actual JSON artifacts generated by Python
function readArtifact(split: string) {
  const dataPath = path.resolve(__dirname, `../../public/data/${split}.json`);
  return JSON.parse(fs.readFileSync(dataPath, 'utf-8'));
}

describe('WorkflowAdapter', () => {
  beforeEach(() => {
    // Mock global fetch to return our local artifact
    global.fetch = vi.fn().mockImplementation(async (url: string) => {
      const splitMatch = url.match(/\/data\/(dev|validation|holdout)\.json/);
      if (splitMatch) {
        const data = readArtifact(splitMatch[1]);
        return {
          ok: true,
          json: async () => data
        };
      }
      return { ok: false, status: 404 };
    });
  });

  it('Valid DEV artifact loads and contains 100 cases', async () => {
    const data = await WorkflowAdapter.loadWorkflowData('dev');
    expect(data.cases.length).toBe(100);
    expect(data.summary.total_cases).toBe(100);
  });

  it('Valid VALIDATION artifact loads and contains 500 cases', async () => {
    const data = await WorkflowAdapter.loadWorkflowData('validation');
    expect(data.cases.length).toBe(500);
    expect(data.summary.total_cases).toBe(500);
  });

  it('Valid HOLDOUT artifact loads and contains 1000 cases', async () => {
    const data = await WorkflowAdapter.loadWorkflowData('holdout');
    expect(data.cases.length).toBe(1000);
    expect(data.summary.total_cases).toBe(1000);
  });

  it('DEV contains 8 demo_story_cases', async () => {
    const data = await WorkflowAdapter.loadWorkflowData('dev');
    const demoCases = WorkflowAdapter.getDemoCases(data);
    expect(demoCases.length).toBe(8);
  });

  it('getCaseByReference returns the correct case', async () => {
    const data = await WorkflowAdapter.loadWorkflowData('dev');
    const targetRef = data.cases[0].operational_reference_id;
    const result = WorkflowAdapter.getCaseByReference(data, targetRef);
    expect(result).not.toBeNull();
    expect(result?.operational_reference_id).toBe(targetRef);
  });

  it('Missing reference returns controlled null behavior', async () => {
    const data = await WorkflowAdapter.loadWorkflowData('dev');
    const result = WorkflowAdapter.getCaseByReference(data, 'NON_EXISTENT_REF');
    expect(result).toBeNull();
  });

  it('Malformed workflow JSON is rejected safely', async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => ({ bad: 'data' })
    });
    
    await expect(WorkflowAdapter.loadWorkflowData('dev')).rejects.toThrow(/Missing or malformed run_metadata/);
  });

  it('Missing required fields are rejected safely', async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => ({
        run_metadata: { split: 'dev' },
        summary: { total_cases: 10 },
        // cases is missing
      })
    });
    
    await expect(WorkflowAdapter.loadWorkflowData('dev')).rejects.toThrow(/Cases is not an array/);
  });

  it('Deterministic case with null investigation is accepted', async () => {
    const data = await WorkflowAdapter.loadWorkflowData('dev');
    const deterministicCase = data.cases.find((c: WorkflowOutput['cases'][0]) => c.reconciliation.route === 'DETERMINISTIC');
    expect(deterministicCase).toBeDefined();
    expect(deterministicCase?.investigation).toBeNull();
  });

  it('AI case with investigation data is accepted', async () => {
    const data = await WorkflowAdapter.loadWorkflowData('dev');
    const aiCase = data.cases.find((c: WorkflowOutput['cases'][0]) => c.reconciliation.route === 'AI_INVESTIGATOR');
    expect(aiCase).toBeDefined();
    expect(aiCase?.investigation).not.toBeNull();
    expect(aiCase?.investigation?.status).toBe('AI_REVIEW_COMPLETE');
  });

  it('Adapter does not mutate the raw workflow object', async () => {
    const data = await WorkflowAdapter.loadWorkflowData('dev');
    const originalLength = data.cases.length;
    WorkflowAdapter.getCases(data);
    expect(data.cases.length).toBe(originalLength);
  });

  it('Repeated loading returns equivalent data', async () => {
    const data1 = await WorkflowAdapter.loadWorkflowData('dev');
    const data2 = await WorkflowAdapter.loadWorkflowData('dev');
    expect(data1.summary.total_cases).toEqual(data2.summary.total_cases);
  });
});
